### PR TITLE
Feature/server stack trace

### PR DESCRIPTION
**Pull request by fastner**
- Allow colored output (stdout and stderr) in hot server mode
- Improves stack traces on server side code

bildschirmfoto 2017-03-08 um 14 51 32

changes to

bildschirmfoto 2017-03-08 um 15 05 29

### CODE REVIEW

**Comment by swernerx** [comment]
Please try to convince me on these changes.

- The stack trace still contains a lot of crap which is probably not related to the actual code the developer has been written.
- The colors with some red in the stacktrace... what is the idea behind this?
- The stack trace still lists build file positions before source file positions. I figure it would be great to have the whole stack trace mentioning source files only.

**Comment by fastner** [comment]
This is the stack trace generated by V8 and annotated by source-map-support. The red highlighted rows are the ones that have a reference to the original code. The other ones are webpack helper code or nodejs code.

I tried to be not too radical but to solve all your proposals/questions every muted line simply should be hidden.

I will change this so the stack trace is much more reduced. Maybe a command line/env option should reenable the whole stack trace if something in webpack code or nodejs code is wrong.

As you see in the first red line the stack name generated by source-map-support is sometimes strange, I will try to figure out what happens there later...

**Comment by fastner** [comment]
Stacktrace is now:
bildschirmfoto 2017-03-08 um 20 43 35

**Comment by swernerx** [comment]
Much better 👍

**Pull request merged**
